
#packages = std.harvest nixpkgs.legacyPackages
# TODO: Import in:
# - ./devshell.nix
# - ./packages.nix
[
      # https://search.nixos.org/packages?channel=unstable&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%22terraform-providers%22%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=alpha_asc&type=packages&query=terraform
      "kubergrunt"
      "terrcognita"
      "terraform-backend-git"
      "terraform-docs"
      "terraform-inventory"
      "terraform-landscape"
      "terranix"
      "terraspace"
      "tf-summarize"
      "tfautomv"
      "tfk8s"
      "tfupdate"
      # --- Security ---
      "terrascan"
      "tfsec"
      # --- Converters ---
      "iam-policy-json-to-terraform"
      "k2tf"
      "terraformer"
      # --- Plugins ---
      "tflint-plugins.tflint-ruleset-aws"
      "tfplugindocs"
      # --- Providers ---
      "terraform-providers.acme"
      "terraform-providers.age"
      "terraform-providers.ansible"
      "terraform-providers.archive"
      "terraform-providers.argocd"
      "terraform-providers.auth0"
      "terraform-providers.aws"
      "terraform-providers.azuread"
      "terraform-providers.azurerm"
      "terraform-providers.azurestack"
      "terraform-providers.bigip"
      "terraform-providers.bitbucket"
      "terraform-providers.cloudflare"
      "terraform-providers.cloudinit"
      "terraform-providers.consul"
      "terraform-providers.datadog"
      "terraform-providers.dns"
      "terraform-providers.dnsimple"
      "terraform-providers.docker"
      "terraform-providers.elasticsearch"
      "terraform-providers.equinix"
      "terraform-providers.external"
      "terraform-providers.fastly"
      "terraform-providers.github"
      "terraform-providers.gitlab"
      "terraform-providers.google"
      "terraform-providers.google-beta"
      "terraform-providers.googleworkspace"
      "terraform-providers.helm"
      "terraform-providers.heroku"
      "terraform-providers.htpasswd"
      "terraform-providers.http"
      "terraform-providers.hydra"
      "terraform-providers.kafka"
      "terraform-providers.kafka-connect"
      "terraform-providers.keycloak"
      "terraform-providers.kubectl"
      "terraform-providers.kubernetes"
      "terraform-providers.libvirt"
      "terraform-providers.linode"
      "terraform-providers.linuxbox"
      "terraform-providers.local"
      "terraform-providers.lxd"
      "terraform-providers.mailgun"
      "terraform-providers.metal"
      "terraform-providers.minio"
      "terraform-providers.mongodbatlas"
      "terraform-providers.namecheap"
      "terraform-providers.netlify"
      "terraform-providers.nomad"
      "terraform-providers.null"
      "terraform-providers.nutanix"
      "terraform-providers.oci"
      "terraform-providers.okta"
      "terraform-providers.oktaasa"
      "terraform-providers.openstack"
      "terraform-providers.ovh"
      "terraform-providers.pass"
      "terraform-providers.postgresql"
      "terraform-providers.powerdns"
      "terraform-providers.rancher2"
      "terraform-providers.random"
      "terraform-providers.remote"
      "terraform-providers.secret"
      "terraform-providers.snowflake"
      "terraform-providers.shell"
      "terraform-providers.sops"
      "terraform-providers.tailscale"
      "terraform-providers.time"
      "terraform-providers.tls"
      "terraform-providers.vpsadmin"
      "terraform-providers.utils"
      "terraform-providers.vault"
      # --- Editor Plugins ---
      "terraform-ls"
      "terraform-lsp"
      "tflint"
      "vimPlugins.nvim-treesitter-parsers.terraform"
      "vimPlugins.vim-terraform"
      "vimPlugins.vim-terraform-completion"
      "vscode-extensions.hashicorp.terraform"
    ]
